pizza_index:
  path: /pizza
  controller: App\Controller\PizzaController::index
  methods: GET

pizza_index_low_price:
  path: /pizza/low-price
  controller: App\Controller\PizzaController::lowPricePizzas
  methods: GET

pizza_create:
  path: /pizza/create
  controller: App\Controller\PizzaController::create
  methods: GET|POST


user_index:
  path: /user
  controller: App\Controller\UserController::index
  methods: GET

user_create:
  path: /user/create
  controller: App\Controller\UserController::create
  methods: GET|POST